### ISSUE TITLE
Artifactory with CHEF

### ISSUE THREAD

**Issue by lmilbaum** [depy-io/depy#394]
{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}

**Comment by lmilbaum** [comment]
2017-08-10 16:36:20,112 depy: module: depy_uri, function: endpoint, message: testing endpoint http://artifactory-server.depy.io:8081/artifactory
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    depy_test.run()
  File "/core/python-modules/test/depy_test.py", line 85, in run
    depy_uri.endpoint("http://artifactory-server.depy.io:8081/artifactory")
  File "/core/python-modules/test/depy_uri.py", line 24, in endpoint
    assert response.status_code == status_code
AssertionError
